[workspace]
members = [
    "icebox",
    "icebox_backend_dumb_dump",
    "icebox_backend_kvm",
    "icebox_core",
    "icebox_os_linux",
    "kvm-common",
    "patch",
    "phys_addr",
]

[profile.dev]
opt-level = 1
